CREATE OR REPLACE EXTERNAL TABLE  DB_BNK_INDIA_{{env_var('SHORT_ENV')}}.SCH_EKIP_SL.STG_LSI_FIX_29_DAILY (
      IE_AFFAIRE VARCHAR as ($1:IE_AFFAIRE::VARCHAR), 
   ID_ELEMENT NUMBER as ($1:ID_ELEMENT::NUMBER), 
   CODE_MOTIF VARCHAR as ($1:CODE_MOTIF::VARCHAR), 
   DATE_TRAITEMENT DATE as (to_date(NULLIF($1:DATE_TRAITEMENT::TEXT,''),'DDMMYYYY')), 
   TIERS_CE VARCHAR as ($1:TIERS_CE::VARCHAR), 
   FLAG_CE VARCHAR as ($1:FLAG_CE::VARCHAR), 
   DATE_CREATION DATE as (to_date(NULLIF($1:DATE_CREATION::TEXT,''),'DDMMYYYY')), 
   DATE_ACCEPTATION DATE as (to_date(NULLIF($1:DATE_ACCEPTATION::TEXT,''),'DDMMYYYY')), 
   TIERS_ACCEPTEUR VARCHAR as ($1:TIERS_ACCEPTEUR::VARCHAR), 
   CODE_ORIGINE VARCHAR as ($1:CODE_ORIGINE::VARCHAR), 
    DATE_BATCH_PARTITION DATE as (TRY_CAST(split_part(split_part(metadata$filename, '/', 4), '=', 2) AS DATE)),
   ROW_NUMBER NUMBER as (metadata$file_row_number), 
   DATE_LAST_MODIFIED TIMESTAMP_NTZ as (metadata$file_last_modified)
    )
    PARTITION BY (DATE_BATCH_PARTITION)
    LOCATION = @DB_BNK_INDIA_{{env_var('SHORT_ENV')}}.SCH_EKIP_SL.STG_S3_INDIA_EKIP/lsi/daily/stg_lsi_fix_29/
    FILE_FORMAT = (TYPE = 'PARQUET');
    COMMENT ON TABLE DB_BNK_INDIA_{{env_var('SHORT_ENV')}}.SCH_EKIP_SL.STG_LSI_FIX_29_DAILY IS 'STG_LSI_FIX_29_INDIA_OUT_DAILY';
    