CREATE OR REPLACE VIEW  DB_BNK_INDIA_{{env_var('SHORT_ENV')}}.SCH_EKIP_SL.VW_STG_LSI_FIX_29_DAILY	
    AS SELECT * EXCLUDE VALUE FROM DB_BNK_INDIA_{{env_var('SHORT_ENV')}}.SCH_EKIP_SL.STG_LSI_FIX_29_DAILY;
    